### ISSUE TITLE
0.2.0 Tracking Issue

### ISSUE THREAD

**Issue by DanielKeep** [DanielKeep/rust-custom-derive#25]
- [x] Switch to using `#[derive(Name!)]` instead of `#[derive(Name)]`.
- [x] Add support for either `#[custom_transform(Name!)]` or `#[Name!]`.
- [x] Future proofing: syntax for *either* invoking a macro on pre-Macros 1.1, or delegating to an actual Macros 1.1 derivation.
- [x] Rename to ~`macro_derive!`~ `macro_attr!`.
- [x] Expand support to all items (because why not?)
- [ ] ~~Expand all existing derivations to support everything reasonable, leveraging `parse-macros`.~~ (This can just be handled separately.)
